/*
 * ARConstant.cpp
 *
 *  Created on: 2017. 8. 8.
 *      Author: lee
 */





#include "ARConstant.h"



const int ARConstant::ARNETWORKAL_MANAGER_DEFAULT_ID_MAX= 256,

  // ARNETWORKAL_Frame_t identifiers
ARConstant::BD_NET_CD_NONACK_ID = 10,
ARConstant::BD_NET_CD_ACK_ID = 11,
ARConstant::BD_NET_CD_EMERGENCY_ID = 12,
ARConstant::BD_NET_CD_VIDEO_ACK_ID = 13,
ARConstant::BD_NET_DC_VIDEO_DATA_ID = 125,
ARConstant::BD_NET_DC_EVENT_ID = 126,
ARConstant::BD_NET_DC_NAVDATA_ID=  127,

  // eARCOMMANDS_ID_PROJECT
ARConstant::ARCOMMANDS_ID_PROJECT_COMMON= 0,
ARConstant::ARCOMMANDS_ID_PROJECT_ARDRONE3= 1,

  // eARCOMMANDS_ID_ARDRONE3_CLASS
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_PILOTING =0,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_ANIMATIONS = 5,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_CAMERA= 1,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_MEDIARECORD= 7,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_MEDIARECORDSTATE= 8,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_MEDIARECORDEVENT= 3,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_PILOTINGSTATE= 4,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_NETWORK= 13,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_NETWORKSTATE= 14,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_PILOTINGSETTINGS= 2,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_PILOTINGSETTINGSSTATE= 6,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_SPEEDSETTINGS= 11,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_SPEEDSETTINGSSTATE= 12,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_NETWORKSETTINGS= 9,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_NETWORKSETTINGSSTATE= 10,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_SETTINGS= 15,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_SETTINGSSTATE= 16,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_DIRECTORMODE= 17,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_DIRECTORMODESTATE= 18,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_PICTURESETTINGS= 19,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_PICTURESETTINGSSTATE= 20,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_MEDIASTREAMING= 21,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_MEDIASTREAMINGSTATE= 22,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_GPSSETTINGS= 23,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_GPSSETTINGSSTATE= 24,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_CAMERASTATE= 25,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_ANTIFLICKERING= 29,
ARConstant::ARCOMMANDS_ID_ARDRONE3_CLASS_ANTIFLICKERINGSTATE= 30,

  // eARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD
ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_FLATTRIMCHANGED= 0,
ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_FLYINGSTATECHANGED= 1,
ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_ALERTSTATECHANGED= 2,
ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_NAVIGATEHOMESTATECHANGED= 3,
ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_POSITIONCHANGED= 4,
ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_SPEEDCHANGED= 5,
ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_ATTITUDECHANGED= 6,
ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_AUTOTAKEOFFMODECHANGED= 7,
ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_ALTITUDECHANGED= 8,
ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_MAX= 9,

  // eARCOMMANDS_ID_ARDRONE3_ANIMATIONS_CMD;
ARConstant::ARCOMMANDS_ID_ARDRONE3_ANIMATIONS_CMD_FLIP= 0,
ARConstant::ARCOMMANDS_ID_ARDRONE3_ANIMATIONS_CMD_MAX= 1,

  // eARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE;
ARConstant::ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_LANDED= 0,
ARConstant::ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_TAKINGOFF= 1,
ARConstant::ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_HOVERING= 2,
ARConstant::ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_FLYING= 3,
ARConstant::ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_LANDING= 4,
ARConstant::ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_EMERGENCY= 5,
ARConstant::ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_MAX= 6,

  // eARCOMMANDS_ARDRONE3_ANIMATIONS_FLIP_DIRECTION;
ARConstant::ARCOMMANDS_ARDRONE3_ANIMATIONS_FLIP_DIRECTION_FRONT= 0,
ARConstant::ARCOMMANDS_ARDRONE3_ANIMATIONS_FLIP_DIRECTION_BACK= 1,
ARConstant::ARCOMMANDS_ARDRONE3_ANIMATIONS_FLIP_DIRECTION_RIGHT= 2,
ARConstant::ARCOMMANDS_ARDRONE3_ANIMATIONS_FLIP_DIRECTION_LEFT= 3,
ARConstant::ARCOMMANDS_ARDRONE3_ANIMATIONS_FLIP_DIRECTION_MAX= 4,

  // eARCOMMANDS_ID_COMMON_CLASS
ARConstant::ARCOMMANDS_ID_COMMON_CLASS_NETWORK= 0,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_NETWORKEVENT= 1,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_SETTINGS= 2,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_SETTINGSSTATE= 3,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_COMMON= 4,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_COMMONSTATE= 5,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_OVERHEAT= 6,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_OVERHEATSTATE= 7,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_CONTROLLERSTATE= 8,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_WIFISETTINGS= 9,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_WIFISETTINGSSTATE= 10,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_MAVLINK= 11,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_MAVLINKSTATE= 12,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_CALIBRATION= 13,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_CALIBRATIONSTATE= 14,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_CAMERASETTINGSSTATE= 15,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_GPS= 16,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_FLIGHTPLANSTATE= 17,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_FLIGHTPLANEVENT= 19,
  ARConstant::ARCOMMANDS_ID_COMMON_CLASS_ARLIBSVERSIONSSTATE= 18,

  // eARCOMMANDS_ID_ARDRONE3_PILOTING_CMD
  ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_FLATTRIM= 0,
  ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_TAKEOFF= 1,
  ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_PCMD= 2,
  ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_LANDING= 3,
  ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_EMERGENCY= 4,
  ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_NAVIGATEHOME= 5,
  ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_AUTOTAKEOFFMODE= 6,
  ARConstant::ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_MAX= 7,

  // eARCOMMANDS_ID_ARDRONE3_MEDIARECORD_CMD
  ARConstant::ARCOMMANDS_ID_ARDRONE3_MEDIARECORD_CMD_PICTURE= 0,
  ARConstant::ARCOMMANDS_ID_ARDRONE3_MEDIARECORD_CMD_VIDEO= 1,
  ARConstant::ARCOMMANDS_ID_ARDRONE3_MEDIARECORD_CMD_PICTUREV2= 2,
  ARConstant::ARCOMMANDS_ID_ARDRONE3_MEDIARECORD_CMD_VIDEOV2= 3,
  ARConstant::ARCOMMANDS_ID_ARDRONE3_MEDIARECORD_CMD_MAX= 4,

  // eARCOMMANDS_ARDRONE3_MEDIARECORD_VIDEO_RECORD
  ARConstant::ARCOMMANDS_ARDRONE3_MEDIARECORD_VIDEO_RECORD_STOP= 0,
  ARConstant::ARCOMMANDS_ARDRONE3_MEDIARECORD_VIDEO_RECORD_START= 1,
  ARConstant::ARCOMMANDS_ARDRONE3_MEDIARECORD_VIDEO_RECORD_MAX= 2,

  // eARCOMMANDS_ID_COMMON_COMMON_CMD
  ARConstant::ARCOMMANDS_ID_COMMON_COMMON_CMD_ALLSTATES= 0,
  ARConstant::ARCOMMANDS_ID_COMMON_COMMON_CMD_CURRENTDATE= 1,
  ARConstant::ARCOMMANDS_ID_COMMON_COMMON_CMD_CURRENTTIME= 2,
  ARConstant::ARCOMMANDS_ID_COMMON_COMMON_CMD_REBOOT= 3,
  ARConstant::ARCOMMANDS_ID_COMMON_COMMON_CMD_MAX= 4,

  // eARCOMMANDS_ID_COMMON_COMMONSTATE_CMD;
  ARConstant::ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_ALLSTATESCHANGED= 0,
  ARConstant::ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_BATTERYSTATECHANGED= 1,
  ARConstant::ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_MASSSTORAGESTATELISTCHANGED= 2,
  ARConstant::ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_MASSSTORAGEINFOSTATELISTCHANGED= 3,
  ARConstant::ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_CURRENTDATECHANGED= 4,
  ARConstant::ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_CURRENTTIMECHANGED= 5,
  ARConstant::ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_MASSSTORAGEINFOREMAININGLISTCHANGED= 6,
  ARConstant::ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_WIFISIGNALCHANGED= 6,
  ARConstant::ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_SENSORSSTATESLISTCHANGED= 7,
  ARConstant::ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_MAX= 8,

  // eARMEDIA_ENCAPSULER_CODEC
  ARConstant::CODEC_UNKNNOWN= 0,
  ARConstant::CODEC_VLIB= 1,
  ARConstant::CODEC_P264= 2,
  ARConstant::CODEC_MPEG4_VISUAL= 3,
  ARConstant::CODEC_MPEG4_AVC= 4,
  ARConstant::CODEC_MOTION_JPEG= 5,

  // eARMEDIA_ENCAPSULER_FRAME_TYPE;
  ARConstant::ARMEDIA_ENCAPSULER_FRAME_TYPE_UNKNNOWN= 0,
  ARConstant::ARMEDIA_ENCAPSULER_FRAME_TYPE_I_FRAME= 1,
  ARConstant::ARMEDIA_ENCAPSULER_FRAME_TYPE_P_FRAME= 2,
  ARConstant::ARMEDIA_ENCAPSULER_FRAME_TYPE_JPEG= 3,
  ARConstant::ARMEDIA_ENCAPSULER_FRAME_TYPE_MAX= 4,

  // eARNETWORK_MANAGER_INTERNAL_BUFFER_ID
  ARConstant::ARNETWORK_MANAGER_INTERNAL_BUFFER_ID_PING= 0,
  ARConstant::ARNETWORK_MANAGER_INTERNAL_BUFFER_ID_PONG= 1,
  ARConstant::ARNETWORK_MANAGER_INTERNAL_BUFFER_ID_MAX= 3,

  // eARNETWORKAL_FRAME_TYPE
  ARConstant::ARNETWORKAL_FRAME_TYPE_UNINITIALIZED= 0,
  ARConstant::ARNETWORKAL_FRAME_TYPE_ACK= 1,
  ARConstant::ARNETWORKAL_FRAME_TYPE_DATA= 2,
  ARConstant::ARNETWORKAL_FRAME_TYPE_DATA_LOW_LATENCY= 3,
  ARConstant::ARNETWORKAL_FRAME_TYPE_DATA_WITH_ACK= 4,
  ARConstant::ARNETWORKAL_FRAME_TYPE_MAX= 5;


